### PR TITLE
Add ASL3 Web Transceiver support

### PR DESCRIPTION
**Pull request by rhgndf**
To use it, add your ASL3 password to the ASL pass below TGIF pass then set username to `allstar-public` and password to `allstar` in the hosts file like so:
`IAX 12345 12345.nodes.allstarlink.org 4569 allstar-public allstar`

### CODE REVIEW

**Comment by HakanKoseoglu** [comment]
This (main) branch hasn't had an update for the last 6 months, but there's an alternative fork being in development which recently had a -lot- of improvements. https://github.com/rohithzmoi/Droidstar-DMR if you are interested...

**Comment by rhgndf** [comment]
Thanks for the heads up, I will try to port it over to that fork.

**Comment by nostar** [comment]
If you get updated and resolve the conflicts, I'll test this out.

**Comment by rhgndf** [comment]
Conflicts are resolved. Not sure if you want to put up ASLHosts.txt also.

**Comment by rhgndf** [comment]
Also, I see your mention of dynarmic: I have a version here that uses it https://github.com/rhgndf/md380emu

**Comment by nostar** [comment]
@rhgndf callingName no longer comes back in the webtransceiver.php file, so this no longer works.  Do you know another way to get it?

**Comment by rhgndf** [comment]
#21

**Pull request merged**
